### ISSUE TITLE
Add supporting sponsor details on /sponsors page

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#101]
Please add the supporting sponsor details to the /sponsors page. 

Since we will soon have 3 sponsors it would be great if we could add the name of the package they've purchased next to their logotype (if possible):
- Emplifi - BAR & BEER SPONSOR - already visible on the website
- mail alliance - SUPPORTING SPONSOR - details below
- TreviPay - HEADLINE SPONSOR - more details TBA

Logotype: https://res.cloudinary.com/ecommerceberlin/image/upload/v1643793763/Logos/mailalliance-logo.png

Description:
mail alliance is specialized in “the last mile”. The Germany-wide dispatch **of mailbox-ready postal and e-commerce items** in all common formats: **trackable e-commerce consignments of goods**, mailings, flyers, coupons & gift cards, magazines and catalogues. We offer our business customers who send large volumes the affordable all-inclusive package - experienced, fast and reliable, from North to South - from West to East - throughout Germany.
As Germany’s large network of private postal service providers, mail alliance has a local presence through regional partners. Thanks to many years of experience and profound expertise, we know exactly what matters when it comes to delivering mailbox-ready items. For the best **“last mile”** service, we **combine central planning expertise with local delivery competence**, thus creating uniform processes with comprehensive quality management. This enables us to offer flexible, customized shipping solutions and optimized postage costs. **Customers save significant amounts of money and are in the best hands.**

**Comment by az** [comment]
@jprzybylski4 next time please make sure that
1. purchase (paid) with proper email address is made... assign a company....fill in the company account with desired texts, logotype
2. send me just the company ID and sponsor description

i am not processing any raw data - this issue is an exception
