### ISSUE TITLE
Add headline sponsor details on /sponsors page and the logotype on the hero widget

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#102]
Re hero widget - it would be great if we could place the logotype like on the virtual website:
![E-commerce Berlin Virtual Edition 2022-03-08 16-04-44](https://user-images.githubusercontent.com/75311923/157265080-069bacfe-44fe-44fd-9101-bab178c5119d.png)

Company description:
[TreviPay](https://www.trevipay.com/) is a global financial technology company specializing in payment and credit management for B2B companies through custom omni-channel payments solutions. We streamline the purchasing experience and support increased customer interaction in B2B Commerce, facilitating $6 billion USD in transactions per year in 18 currencies for customers in more than 27 countries. To learn more about TreviPay, please visit [TreviPay.com](http://trevipay.com/).

[TreviPay_Logo_Color-500px.eps.zip](https://github.com/ecommerceberlin/ecommercegermanyawards.com/files/8207289/TreviPay_Logo_Color-500px.eps.zip)

**Comment by az** [comment]
@jprzybylski4 done. related https://github.com/ecommerceberlin/ecommercegermanyawards.com/issues/105
