### ISSUE TITLE
update all legal files

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#112]
@marek-berlin source files - https://github.com/ecommerceberlin/ecommercegermanyawards.com/tree/main/texts 

if you need to update any of above files DOWNLOAD, edit in markdown (iA writer) or text (for devs!!!! editor like sublime or visual studio code) and append updated files HERE.... as comments

**Comment by marek-berlin** [comment]
[contest.md](https://github.com/ecommerceberlin/ecommercegermanyawards.com/files/9424802/contest.md)

**Comment by marek-berlin** [comment]
[visitors-data.md](https://github.com/ecommerceberlin/ecommercegermanyawards.com/files/9424922/visitors-data.md)

Change Linkedin to Facebook
Mentioning the Awards

**Comment by marek-berlin** [comment]
The rest of the files are fine and they are actual

**Comment by az** [comment]
via 8ebac4627fc412df52eb4c5bb42493a08bcf0b9d
