### ISSUE TITLE
WYCIĄGU Z REGULAMINU / przy formularzu do zapisu

### ISSUE THREAD

**Issue by marek-berlin** [ecommerceberlin/ecommercegermanyawards.com#124]
As far as I know - tego się nie da edytować w localize.

→ Jak jest:
Other participants will be required to pay a participation fee of 400 EUR for the submission in the first category, and (if applicable) 200 EUR in the second category, in case they are chosen as one of the top10 companies in the category and get through to the second round of the E-commerce Germany Awards co
To bym chyba przeformułowała, żeby nie odstraszać ceną. Jak proponuję (inny szyk zdania = inny nacisk = inne wrażenie):
ENG
Other participants will be required to pay a participation fee, but only in case they are chosen as one of the top10 companies in the category and get through to the second round of the E-commerce Germany Awards contest (i.e. jury voting); the fee is 400 EUR for the submission in the first category, and (if applicable) 200 EUR in the second category.
DE
Alle anderen Teilnehmer müssen eine Teilnahmegebühr begleichen, allerdings nur dann, wenn sie unter die Top 10 der Kategorie gewählt werden und in die zweite Runde des Wettbewerbs um den E-Commerce Deutschland Preis kommen (d.h. Jury-Voting); die Gebühr beträgt 400 EUR für die Einreichung in der ersten Kategorie und (ggf.) 200 EUR in der zweiten Kategorie.

→ Jak jest:
Each participant of the second round will receive 2 Tickets for the E-commerce Germany Awards Ceremony and Networking Party included in the participation fee. 
Wg mnie to nie jest klarowna informacja, ponieważ exhibitors w ogóle nie płacą fee, stąd mogą się zastanawiać, czy też dostaną bilety; jak proponuję:
ENG
Each participant of the second round will receive 2 free tickets for the E-commerce Germany Awards Ceremony and Networking Party.
DE
Alle Teilnehmer der zweiten Runde erhalten 2 kostenlose Eintrittskarten für die Preisverleihung am Networking-Party und die E-commerce Germany Awards.

→ Jak jest:
If a particular company wins, but there is a possible suspicion regarding the participant’s activity in the contest, the Organiser has the right to verify or cancel the submission during or after the Contest.
Wg mnie nie jest to jasne, proponuję doprecyzować, np.:
ENG
The Organiser reserves the right to disqualify any submission in the Contest or entitlement to a prize, if, in the sole discretion of the Organiser, it determines or suspects that the entrant has attempted to undermine the legitimate operation of the Contest by cheating, hacking, deception, or other fraudulent, deceptive, or unfair playing practices.
DE
Der Veranstalter hat das Recht, Bewerbungen am Wettbewerb oder den Anspruch auf einen Preis zu disqualifizieren, wenn er nach eigenem Urteil feststellt oder vermutet, dass der Teilnehmer versucht hat, den rechtmäßigen Ablauf des Wettbewerbs durch Betrug, Hacking, Täuschung oder andere betrügerische, täuschende oder unfaire Spielpraktiken zu beeinträchtigen.

**Comment by az** [comment]
@marek-berlin i wrote in /about related issue that only that section contains non-localise content so.....

**awards.rules-summary.body**

protip (use some really distinctive and short phrases to match via search engines...because for instance markdown markup or linebreaks can change the results)

**Comment by az** [comment]
@marek-berlin klar? updated? can i close this?

**Comment by marek-berlin** [comment]
yes, updated and klar :)

I couldn't find it even though I have tried different parts of the text.
