### ISSUE TITLE
(UX) Jury - remove bio '...' 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#134]
@az 
REMOVE 
We removed bio section from the jury ticket but there are still '...' below the title. 

May we remove these three dots '...' from everywhere? 

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/118257251/203538132-00058a96-0eee-447e-a3b4-387a95043252.png">

**Comment by az** [comment]
@klaudia2209 prefix all issues with labels we discussed.... i assume this is a (BUG) - it helps me scan items quickier (if i see (BUG) i try to process things asap....of course (BUG) has specific template (we have discussed it ) but in this case everything is "black on white" so such quick note is OK)

**Comment by klaudia2209** [comment]
Ok, sure, thank you.
