### ISSUE TITLE
(BUG) The same text (year 2022) under different editions

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#137]
PAST WINNERS: 

There is the same title with 2022 under different, previous editions: 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/118257251/203578399-dd97747e-648a-4373-8f11-cc0bc60cade2.png">

**Comment by az** [comment]
BUG = something that should WORK (enable some kind of action...) does not work
