### ISSUE TITLE
(BUG) About & Register page - they didn't update after changes on homepage

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#138]
Yesterday me and Aleksandra uploaded changes in loco. 

We noticed that changes we uploaded on the homepage, didn't appear on the Register and About pages. Even when we changed the footer, changes are not visible on these pages (About and Register). Here is an example: 

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/118257251/203753204-aa88fa07-5199-422f-871c-f043a3b50fd7.png">

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/118257251/203752997-7731fca5-5036-4385-b934-d36cd8e1bf13.png">

**Comment by az** [comment]
@klaudia2209 probably some infrastructure problem (no self-refreshing) - please let me know on SLACK / ecommerceberlin_it EACH TIME you change some texts in localise and i will force refresh
