### ISSUE TITLE
(IDEA) Home - EGA CONTEST CATEGORIES - POP-UP 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#139]
Can we remove "...(more)" and instead of this, create one of these solutions? 

1) Make a title clickable and bold to show the user that is clickable. After click on the title, the pop-up appear 
2) move "more" to the next line and make it bold (highlighted in some way) and clickable and after clicking on it the pop-up appear 

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/118257251/203573154-921e8cd0-9b6e-429a-b0ef-4c42db6bf26d.png">

**Comment by az** [comment]
nie. za duzo przeróbek...poza tym tłuste nagłówki byłyby (IMO :) przytłaczające...
