### ISSUE TITLE
Change the event date

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#14]
Event date change to: May 26
![Mark_screen](https://user-images.githubusercontent.com/75311923/101766195-bb0ad000-3ae2-11eb-9bf9-ef99b2607816.png)

**Comment by az** [comment]
where does it come from? cannot find any reference to that date.....

https://developers.facebook.com/tools/debug/?q=http%3A%2F%2Fecommercegermanyawards.com%2Fvote

![Sharing Debugger - Facebook for Developers 2021-01-21 01-55-46](https://user-images.githubusercontent.com/2198/105259270-cba37100-5b8b-11eb-9597-27e2a83e797b.png)

**Comment by jprzybylski4** [comment]
I couldn't find it either, but that how Google was showing the result. 
It doesn't anymore - I don't know what happened here but now it's all good
![ecommerce germany awards](https://user-images.githubusercontent.com/75311923/105511377-1cbc7d80-5cd0-11eb-8051-77d86c4b34cb.png)
