### ISSUE TITLE
(MAINTENANCE) - FAQ - add to the homepage and Vote page 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#143]
FAQ can be added to **homepage** above **WINNERS OF E-COMMERCE GERMANY AWARDS 2022** and **Vote** page above the **WINNERS OF E-COMMERCE GERMANY AWARDS 2022**

**Comment by az** [comment]
i think it should be divided into "submission -related FAQ" and "voting-related FAQ"
