### ISSUE TITLE
(UX) homepage - similar font size - (cosmetic stuff)

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#147]
These changes are not so important, I am aware of that. But if you find some free time and if you would like to change it, I was thinking about some consistency on the page. We can for example have less font sizes. 

Elements with green frame - the same size 
Elements with orange frame - the same size 

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/118257251/203797471-80836db7-970b-498f-aefc-a12cbfdc5376.png">

**Comment by az** [comment]
@klaudia2209 normally we handle such issues in more free time (like between warsaw editions - like in the summer) ... no NO TIME... i add it this to "UX" milestone

**Comment by klaudia2209** [comment]
Ok, sure, thank you
