### ISSUE TITLE
(QUESTION) EGA category ar_vr_3d - Best Product Content Creation Tool

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#148]
We added 'ar_vr_3d' in the assets and translate. It's shown correctly on the public website. But in the panel when we changed "ar_vr_3d" to "Best Product Content Creation Tool" it's still visible as ar_vr_3d. 

When we make a test registration and receive an-e-mail, the name of the category is visible in as "ar_vr_3d". 

Can we do anything with that, please? 

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/118257251/205035356-34c70206-9be1-4530-a115-59567995a860.png">

**Comment by az** [comment]
@klaudia2209 its OK...it is as it should be ... translations are for front-end / human, internally it is stored as "meaningful keywords" + localise has nothing to do with the admin panel


if you want to translate what is displayed we have it here https://pages.ecommerceberlin.com/admin/inputedit/236 (do not mess with that ... just click edit label and correct translations - FOR ACCOUNTS)

**Comment by klaudia2209** [comment]
Hello, @az I think that there is some problem with this category, because it doesn't change and it is still in EGA pages and it's visible in the received e-mail. Do you have some time to take a look at this? 

<img width="857" alt="image" src="https://user-images.githubusercontent.com/118257251/205638992-2481d067-ee87-49f7-b983-246486233ddc.png">

<img width="1336" alt="image" src="https://user-images.githubusercontent.com/118257251/205639053-c50ddc93-9ff4-489b-afcd-fe9677da6e25.png">

**Comment by az** [comment]
@klaudia2209 
i have found the problem

instead of "ar_vr_3d" in admin input setting we had "a**v**_vr_3d" so from the admin side its now OK

proof

![changefields?token=6a4773a827a49dc0713aade0651138f0a033b275 2022-12-05 14-00-52](https://user-images.githubusercontent.com/2198/205643697-9d1e2b03-8d14-4389-99e8-15d71b4791ad.jpg)

as for email confirmation - i dont think we have translated "inputs" there .... it must stay as it currently is (we could remove it completely but for companies that submitted more than 1 application it is better to have such "encrypted" info than none)

**Comment by klaudia2209** [comment]
@az I know that I bother you in this case, but there are actually 2 categories like this and information is taken from this "ar_vr_3d" category instead of this: "best_product_content_creation_tool"

<img width="478" alt="image" src="https://user-images.githubusercontent.com/118257251/205874836-367d0f57-6de6-410b-b0df-50a271888cef.png">

<img width="955" alt="image" src="https://user-images.githubusercontent.com/118257251/205876256-362e6db1-db72-4a99-b92d-9fe29a9bdbe9.png">

**Comment by az** [comment]
@klaudia2209 the one is only in admin as a consequence of translation of "bad option".
AGAIN - what is the real problem? what is the thing you cannot do?

**Comment by az** [comment]
@klaudia2209 the most important issue is that you SHALL NOT MESS with categories in admin (who the fuck added "best_product_content_creation_tool"?)

these are categories that we have in the front (website)
![WidgetRegForm js — vsc (obszar roboczy) 2022-12-06 11-32-06](https://user-images.githubusercontent.com/2198/205887573-b3c041f3-175e-4ef1-b4fc-7b3ee873010a.jpg)

and in admin we MUST HAVE THE SAME....i really do not know who added "best_product_content_creation_tool" and why we have such submissions in the admin? you must have edited the applications and choose option that is not present publicly

**Comment by az** [comment]
i believe "ar_vr_3d" was to be translated "best product content creation tool" and another option is something you had (wrongly) added

**Comment by klaudia2209** [comment]
hello @az

just to be 100% sure, I talked to Aleksandra and she would like to prepare EGA on the highest level and make a great impressions on the participants.

If the participant, submitting for this category receives a confirmation e-mail with “ar_vr_3d” being shown as a category, he doesn’t know and can’t check if he has chosen the category he intended to. The same for us, when exporting the submissions from pages to excel, we see all the names of the categories normally except for this one.

so to ensure ourselves - will you be able to change it or it should stay like this? Or can I change it somewhere? 

<img width="958" alt="image" src="https://user-images.githubusercontent.com/118257251/206152670-c30090ff-8fb4-4a3a-9f23-ad2c1da427e7.png">
