### ISSUE TITLE
(MAINTENANCE) - **EGA** - adding ASSOCIATION PARTNERS section on the main page

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#150]
Hello @az,

I have the same issue in case of EGA website - adding 'ASSOCIATION PARTNERS' section to the main page, above 'MEDIA PARTNERS'. Formating of the title - the same like other partners

**Comment by az** [comment]
resolved via 8ca8af305cffe13465d004ff37b8384d896d00fb

**Comment by az** [comment]
commit 8ca8af305cffe13465d004ff37b8384d896d00fb

**Comment by az** [comment]
@klaudia2209 no problem
1. add new to the pool - https://admin.ecommercegermanyawards.com/admin/resources/partners
2. select those you want to display in association section in https://admin.ecommercegermanyawards.com/admin/widget/3576?updated

**Comment by az** [comment]
@klaudia2209 of course please translate section title on www (i will not create separate issue for that :)
