### ISSUE TITLE
(MAINTENANCE) adding the sponsors' logo 2023 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#151]
Hello, @az 

I would like to ask you to place main sponsor logo in three places on the website. 

Could you make changes on the sponsors page (https://ecommercegermanyawards.com/sponsors)? 

1) Add main sponsor logo on the EGA's website: 

Headline Sponsor 2023 
Nexi (logo package attached)
Description EN (it may changed): 

We are The European PayTech with scale, capabilities, and proximity to provide the simplest, fastest and safest payment solutions to People, Businesses and Financial Institutions. We come from the merger and integration of Nexi, Nets/Concardis and Sia, among the biggest European players in digital payments and we are now present in more than 25 countries.

[NEXI (2).zip](https://github.com/ecommerceberlin/ecommercegermanyawards.com/files/10307231/NEXI.2.zip)

2) Remove the sponsors from 2019, 2020 and 2021

**Comment by klaudia2209** [comment]
Secondly - add the logo on the main page (Aleksandra heard that it was like this in previous year): 

![Zrzut ekranu 2022-12-27 o 09 36 33](https://user-images.githubusercontent.com/118257251/209646453-6bdcaf33-c66c-4d4e-9d89-56dc97cba461.png)

**Comment by klaudia2209** [comment]
Last but not least: 

Add sponsor's section above the partners' section: 

![Zrzut ekranu 2022-12-27 o 09 39 02](https://user-images.githubusercontent.com/118257251/209646674-fbe0d020-f5d0-4e3c-91e9-e1d9c0e680a3.png)

**Comment by klaudia2209** [comment]
Hello, @az

Here is another sponsor's logo and the description to add, when you will have some time. Thank you. 

Bar & Beer Sponsor 2023
Taxually 

LOGO: 
![Taxually_logo_color (2)](https://user-images.githubusercontent.com/118257251/211536345-d8070605-ccac-4ad1-91bb-8e22d20b054c.svg)
![Taxually_logo_color (3)](https://user-images.githubusercontent.com/118257251/211536347-6c7711fa-fa38-4da7-9eec-3218298d6f6a.png)

DESCRIPTION:
We are Taxually, a Budapest-based, technology-led company working to give our clients the very best in VAT compliance services. 

Since 2018 our focus has been on the development of state-of-the-art software that allows our clients, big and small, to concentrate on building and expanding their businesses without worrying about tax or VAT compliance issues.

Our multi-disciplinary, remote-first team is based all over the world and includes experienced accountants and tax advisors boasting over 35 years in the industry between them. We provide our services to more than 50 countries worldwide, helping a wide range of companies expand into global markets by simplifying the tax and VAT compliance process, so they can get on with the job of growing their business.

**Comment by klaudia2209** [comment]
DJ Sponsor 2023
Actindo Core 

Actindo Core1 is the first MACH alliance certified composable ERP, PXM & OMS for 360° unified commerce. It is the central platform for all integrations and gives brands the ability to use their data, accelerate workflows and orchestrate processes across systems, touchpoints, databases and many more. It is easy to apply as we use low-code to address the individual needs and it can be tailored to any workflow as every component is pluggable, scalable, and replaceable. Our technology allows brands and retailers to choose the technology they need to stay relevant and launch fast. Trusted by the world ́s leading companies: Nintendo, ABUS, Mondelez, Nestle, TANITA, ETERNA & Braun Büffel.

![Actindo Logo-01](https://user-images.githubusercontent.com/118257251/213155196-24ef687f-0ef0-4a5c-b7e5-af1bdffcff06.svg)

Link do wszystkich logo: https://drive.google.com/drive/u/0/folders/1-qa3V8lUjuOOtkb4bRSfJKjEbXOu1lb0

**Comment by az** [comment]
@klaudia2209 "adding the sponsors' logo 2023" dodane.... issue musi byc "atomowe" - jesli chodzi o aktualizacje podstrony sponsors stworz prosze osobny/osobne issues ..

"Remove the sponsors from 2019, 2020 and 2021" to nie bedzie zrealizowane
