### ISSUE TITLE
(BUG) lines overlap the text in the EGA form 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#152]
title
lines overlap the text in the EGA form (URL - logo and video)
 
environment (chrome/safari/firefox/msie, etc)
chrome

expected result
text separated from the lines 

actual result
lines overlap the text in URL sections (logo and video) 

steps to reproduce
example: click on the sign-in link with token

(dont paste links with sign-in TOKENS....u may paste them on slack - in the thread, after creating this issues)

proof 
<img width="750" alt="Zrzut ekranu 2022-12-30 o 13 46 30" src="https://user-images.githubusercontent.com/118257251/210085393-1bcb62ba-fb93-4253-a24c-bea05bbd8f3f.png">

Severity/Priority
small

Trivial (fixing this would leverage UX)

number of users already affected (reporting this issue) of total users
2

team members who tested (apart from creator of bug report)
AD/KC

**Comment by az** [comment]
@ klaudia2209 nie mozna zmienic tlumaczenia pola? to sa „kontrolki”
formularza z biblioteki - antyUXowe sa przede wszystkim takie objasnienia
pola forma - musza byc 1 linijkowe
-- 
Regards / Pozdrawiam,

Adam Zygadlewicz

mobile: +48 605 501 601
skype: adam.zygadlewicz
http://fb.me/adam.zygadlewicz
http://twitter.com/az

**Comment by az** [comment]
@klaudia2209 poprawiono tlumaczenia?

**Comment by klaudia2209** [comment]
Aleksandrze zależało, żeby był cały tekst, jeśli to nie możliwe, to Ola w wolnej chwili zmieni tłumaczenia

**Comment by az** [comment]
@klaudia2209 "no i?" BUGiem jest za długa nazwa pola. to nie jest miejsce na "historyjki" i ubieganie ew customer supportu.
