### ISSUE TITLE
(MAINTENANCE) - can we remove 'voting %(votes)'? 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#163]
Hello, @az 

I have a question from the team - can we make "%(votes)" invisible after voting? It looks for the user a little bit like a bug. 

![image](https://user-images.githubusercontent.com/118257251/211793071-78d533c4-4978-4fd2-af1d-ae7ec67196ff.png)

**Comment by az** [comment]
@klaudia2209 przyszłościowo odpal proszę localise i wpisz "votes" w search, ok?

**Comment by klaudia2209** [comment]
ok, czaję, wystarczyło tam to zmienić... będę wiedzieć na przyszłość
