### ISSUE TITLE
(MAINTENANCE) showing the number of voices on the website in EGA competition 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#164]
Cześć, 

mam prośbę od zespołu o pokazanie liczby głosów na stronie, które zdobyły firmy w konkursie EGA. 

Aleksandra chce im dać info, że ich głosy są widoczne i zmotywować ich do pracy ;)

**Comment by az** [comment]
oki, jutro--
Regards / Pozdrawiam,

Adam Zygadlewicz

mobile: +48 605 501 601
skype: adam.zygadlewicz
http://fb.me/adam.zygadlewicz
http://twitter.com/az
