### ISSUE TITLE
(maintenance) add Nexi logo on the homepage 

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#167]
Prośba o dodanie tekstu "Main sponsor" + logo sponsora Nexi nad sekcją "ASSOCIATION PARTNERS" 

![image](https://user-images.githubusercontent.com/118257251/214242090-3afc91a1-a73c-4ec5-b432-aec9c46a2204.png)

[NEXI (2).zip](https://github.com/ecommerceberlin/ecommercegermanyawards.com/files/10307231/NEXI.2.zip)

**Comment by az** [comment]
@klaudia2209  cc @KarolinaTEH 

procedura taka sama jak w przypadku media - 
dodac do bazy partnerow - https://admin.ecommercegermanyawards.com/admin/resources/partners
dodac do widgetu "sponsors" - https://admin.ecommercegermanyawards.com/admin/widget/3577?updated
przetlumaczyc header widgetu na www wedle uznania

**Comment by az** [comment]
![E-commerce Germany Awards | Berlin | February 22, 2023 2023-01-30 15-46-55](https://user-images.githubusercontent.com/2198/215509346-b188ece5-1aa7-4346-b61a-1097ca41ec0a.jpg)

**Comment by az** [comment]
related https://github.com/ecommerceberlin/ecommercegermanyawards.com/issues/172
