### ISSUE TITLE
Sponsors' Profiles 

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#17]
Profiles like Participant Profile - not just a link to the website

**Comment by az** [comment]
why dont you just register them via dedicated ticket so we could just list them as we do with exhibitors @jprzybylski4 ?

**Comment by jprzybylski4** [comment]
Sounds fine to me. In this case, can we create a Sponsor's Profile - much like the Exhibitor's Profile? 
So that by clicking on their logotype the user is not directed to the sponsor's website but to the Profile on our website?

**Comment by az** [comment]
@jprzybylski4 yes....  there is a ticket called "fake company reg" with cost 1... which allows to register via https://admin.ecommercegermanyawards.com/admin/booking and assign a new company.... if company exists (for instance in EBE context - please let me know - we will re-use it)
