### ISSUE TITLE
add nexi logo to partners ("old admin")

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#172]
procedura taka sama jak w przypadku media -
dodac do bazy partnerow - https://admin.ecommercegermanyawards.com/admin/resources/partners
dodac do widgetu "sponsors" - https://admin.ecommercegermanyawards.com/admin/widget/3577?updated
przetlumaczyc header widgetu na www wedle uznania

**Comment by az** [comment]
![E-commerce Germany Awards | Berlin | February 22, 2023 2023-01-30 15-46-55](https://user-images.githubusercontent.com/2198/215592678-5a4ab76d-1882-46d6-89dc-5aa5627011c5.jpg)

**Comment by KarolinaTEH** [comment]
done
