### ISSUE TITLE
(maintenance) add new sponsor on the EGA sponsors' page

### ISSUE THREAD

**Issue by klaudia2209** [ecommerceberlin/ecommercegermanyawards.com#174]
Supporting sponsor Avask

We are AVASK, an international firm of accountants and tax experts with a well-reputed specialism in global e-commerce expansion, international taxation, accountancy and business consultancy and advisory services.

AVASK Accounting & Business Consultants work with the most outstanding and proactive professionals to deliver excellent value for more than 8,000 e-commerce sellers and companies across the world. We have a presence in the UK, Europe, the USA, UAE, China and Australia and our collective eyes are set on the horizon looking for new marketplaces and opportunities to enhance and enable our clients’ businesses to flourish and grow.

![Blue AVASK Logo 2021 (1)](https://user-images.githubusercontent.com/118257251/217785793-f3df2490-0610-4300-8094-29609ed78108.svg)

***
Ten sponsor nie jest wystawcą, finalista EGA.

**Comment by KarolinaTEH** [comment]
company ID: 2047
