### ISSUE TITLE
Change background video

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#18]
Last year's reel:
https://www.youtube.com/watch?v=pLfnx7B3BBA&t=1s

**Comment by az** [comment]
@jprzybylski4 will you provide it or shall i close this issue?

**Comment by jprzybylski4** [comment]
https://drive.google.com/file/d/1X8yrJIr8cIOZ6so4DzQdKCiehtV09s1o/view?usp=sharing

**Comment by az** [comment]
e2bead54b8d8c641ff0b79ed2d37af2ab345850f
