### ISSUE TITLE
(IDEA) hide organizer info from the footer 

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommercegermanyawards.com#191]
@az as I'm not able to create PR with WidgetFooter.js changes

part to be hidden:

```
items={[
        {
        secondary: 'event.organizer.name',
        primary: organizer_name
        },

        {
        secondary: 'event.organizer.address',
        primary: organizer_address
        },

        {
        secondary: 'event.organizer.registration',
        primary: organizer_regno
        }
      ]}
```
same for EBE: https://github.com/ecommerceberlin/ecommerceberlin.com/issues/376

**Comment by az** [comment]
@KarolinaTEH (MAINTENANCE) - added subpages, changing settings, changing widget order..... this type of work is hardcore programming (which starts as IDEA :)
