### ISSUE TITLE
(MAINTENANCE) check linkedin app before voting starts (8.01)

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommercegermanyawards.com#194]

**Comment by KarolinaTEH** [comment]
@az podbijam, żeby nie umknęło ;)

**Comment by KarolinaTEH** [comment]
@az i one last reminder przed poniedziałkowym startem głosowania (w poniedziałek rano wrzucę PR z updatem strony)

**Comment by az** [comment]
@KarolinaTEH 
as of the 6th of Jan it works :)

(btw.. there is a string that needs translation)


![ February 21, 2024 🔊 2024-01-06 14-43-18](https://github.com/ecommerceberlin/ecommercegermanyawards.com/assets/2198/6ddfe6b7-bcc6-4ccf-b753-c7c04896ccb8)
