### ISSUE TITLE
(IDEA) create mobile tickets for EGA party participants 

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#201]

**Comment by az** [comment]
@KarolinaTEH 

https://tickets.ecommercegermanyawards.com/rkeeda/ega
https://tickets.ecommercegermanyawards.com/xgavqq/ega

registrations from both projects are supported (event and role info are added)

output is an IMAGE... so plain URL can be sent (Click this URL and show ticket to the staff)... or some more sophisticated HTML message with <img src="_TICKET_URL__ /> to have it embedded (but please remember email clients do not display external images from unknown sources by default)

<img src="https://tickets.ecommercegermanyawards.com/xgavqq/ega" alt="" />

**Comment by KarolinaTEH** [comment]
great - thats's exactly what's needed, thank you
