### ISSUE TITLE
(MAINTENANCE) create 2025 event

### ISSUE THREAD

**Issue by KarolinaTEH** [ecommerceberlin/ecommercegermanyawards.com#205]
& clone tickets, ticket groups, widgets

**Comment by KarolinaTEH** [comment]
@az

**Comment by KarolinaTEH** [comment]
@az the venue is confirmed (spindler&klatt), so it would be great to have premium services on the website. If you don't have time in the upcoming days, I can copy tickets and proceed with the past event for now

**Comment by az** [comment]
@KarolinaTEH cloned. sorry for delay.
