### ISSUE TITLE
Past sponsors page

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#21]

**Comment by az** [comment]
elaborate on this plz @jprzybylski4 

sponsorship type + logotype would be sufficient?

**Comment by jprzybylski4** [comment]
Yes - for past sponsors we don't even need the sponsorship type so far - we only had one sponsor per edition.
If we could have a logotype + short text it would be Perfect. Kind of like here:
https://www.ecommerceawards.london/sponsors/

**Comment by az** [comment]
resolved via https://github.com/ecommerceberlin/ecommercegermanyawards.com/issues/79
