### ISSUE TITLE
incomplete/outdated/misleading translations

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#23]
"awards.contestants.voting-rules.description"  as seen on /vote & /vote/categories/sales_generation etc

**Comment by az** [comment]
![E-commerce Germany Awards | Berlin | May 26, 2021 2021-01-21 01-43-30](https://user-images.githubusercontent.com/2198/105258452-191ede80-5b8a-11eb-899e-24de62500e08.png)
@jprzybylski4

**Comment by jprzybylski4** [comment]
solved
