### ISSUE TITLE
Add video embed

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#25]

**Comment by az** [comment]
![ May 26 2021-01-28 23-40-37](https://user-images.githubusercontent.com/2198/106207558-3d01a600-61c2-11eb-847f-02ff4e4a651d.png)

done (YT and vimeo only) (testing needed @jprzybylski4 )

**Comment by jprzybylski4** [comment]
vimeo and YT work fine - there's just a need to adjust the size. It looks like that on smaller screens:
![Uploading Bildschirmfoto 2021-02-01 um 10.05.52.png…]()

**Comment by jprzybylski4** [comment]
vimeo and YT work fine - there's just a need to adjust the size. It looks like that on smaller screens:
![Uploading Bildschirmfoto 2021-02-01 um 10.05.52.png…]()

**Comment by az** [comment]
![ May 26 2021-02-01 12-43-38](https://user-images.githubusercontent.com/2198/106454556-348fc080-648b-11eb-9a19-95946d92c4cb.png)

should be ok now (responsive)
