### ISSUE TITLE
add video embed for ceremony

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#34]

**Comment by jprzybylski4** [comment]
Ceremony will be streamed on May 26th at 1 PM

**Comment by jprzybylski4** [comment]
YT URL (premiere set to 26th May at 1 PM
https://youtu.be/bAJOeLNOhss

**Comment by az** [comment]
49b62f35840cbf60f87ba55e10ffdf08c8fb931c
