### ISSUE TITLE
update gfx for /about $10$

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#48]

**Comment by jprzybylski4** [comment]
![wykresy_2022_NumberOfContestVoters](https://user-images.githubusercontent.com/75311923/133487052-639141ff-9f13-4a69-93ed-aa4199e00be8.jpg)
![wykresy_2022_NumberOfContestParticipants](https://user-images.githubusercontent.com/75311923/133487070-9071a91c-43fa-4fa3-9c97-28566909131b.jpg)

**Comment by az** [comment]
@jprzybylski4 always provide me  this kind of GFX as scalable/vector format ... links are preferred.

**Comment by jprzybylski4** [comment]
No of participants:
https://drive.google.com/file/d/1UkGuUHbnDopgUJ5EISv49pHHdeM18XOd/view?usp=sharing
No of Voters:
https://drive.google.com/file/d/1q7Fc0wYaqgBFGdYd5RSh96cs9uAgsvQ1/view?usp=sharing

**Comment by az** [comment]
thx
