### ISSUE TITLE
opengraph template update

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#65]

**Comment by az** [comment]
@jprzybylski4 bad date!

**Comment by jprzybylski4** [comment]
![awards-vote-template](https://user-images.githubusercontent.com/75311923/139708344-06ff51be-20dd-4ea0-a590-fede9dbc6a41.png)

**Comment by az** [comment]
354bb63b050e706f3f41c0d3b0c7924524ded03b
