### ISSUE TITLE
translations needed

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#75]
menu item

![E-commerce Germany Awards | Berlin | February 8, 2022 2021-10-29 18-45-01](https://user-images.githubusercontent.com/2198/139472451-2f3c2b78-d838-4d3b-b954-6571a170b2a3.jpg)

/categories

![E-commerce Germany Awards | Berlin | February 8, 2022 2021-10-29 18-46-21](https://user-images.githubusercontent.com/2198/139472625-ffc1110b-1cec-4d46-ae68-81f97b92b0d1.jpg)

**Comment by jprzybylski4** [comment]
done
