### ISSUE TITLE
icons needed

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#76]
for 2 new categories

![E-commerce Germany Awards | Berlin | February 8, 2022 2021-10-29 18-46-21](https://user-images.githubusercontent.com/2198/139472746-81d5a755-d728-417c-952a-a348a47234dc.jpg)

**Comment by jprzybylski4** [comment]
Best Omnichannel Solution - ShoppingBasket
Best Product Content Creation Tool - CameraAlt

**Comment by az** [comment]
f98d652bc5d54d7d3d3e780183d72aba3c184d38
