### ISSUE TITLE
Update "support" details in the footer $30$

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#78]
Please change the personal details to:

Marta Masternak Key Account Manager +49 30 2555 987

https://res.cloudinary.com/ecommerceberlin/image/upload/v1636131391/Awards%20website/received_1343879069033116.jpg

**Comment by az** [comment]
c1646a3bbfa9f7b7c4dc18b1ed504fc41e0a978d
