### ISSUE TITLE
translations, company profile data for sponsors page

### ISSUE THREAD

**Issue by az** [ecommerceberlin/ecommercegermanyawards.com#80]
https://ecommercegermanyawards.com/sponsors

translations needed:

- awards.sponsors.list.title
- awards.sponsor.year (year is passed via code ... use %{data} placeholder in the translation to use it)

company logotype and info

- emplifi (company panel sign in link is provided in the EGA admin emplifi purchase comments)

**Comment by jprzybylski4** [comment]
Done - the only thing about 2022 edition. We will most likely have one more sponsor. Will it be added automatically after the purchase or will I need to ask you to edit the page?

**Comment by az** [comment]
@jprzybylski4 i must add them manually as widgets are invoked per company ID

**Comment by az** [comment]
@jprzybylski4 shall we add some menu item for /sponsors?
