### ISSUE TITLE
EGA vote page bug

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#83]
title
EGA /vote/categories/... pages don't work yet

environment 
Chrome

expected result
Showing the list of companies participating in the contest in chosen category

actual result
Showing the following error:
Application error: a client-side exception has occurred (see the browser console for more information).

steps to reproduce
visit /vote subpage, choose one of the categories.

proof
![Application error: a client-side exception has occurred 2021-11-29 17-21-00](https://user-images.githubusercontent.com/75311923/143904366-b6732070-18d0-4899-9003-0d6002e64d3a.png)

Severity/Priority
Critical 

number of users already affected (reporting this issue) of total users
3 / 200

team members who tested (apart from creator of bug report)
MT, GY

**Comment by az** [comment]
fixed 2c65e94605b1892daa4c87bd1bdef6599376a555
