### ISSUE TITLE
EGA voting bug

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#88]
title
EGA voting worked well in the morning, crashed for 15 minutes, works well again. Just want to make sure everything is fine and the votes are added

environment
Chrome/Safari

expected result
Casting a vote 

actual result
Unable to load / Error 502

steps to reproduce
Load participant's page / press "vote with LinkedIn" button
ie. https://ecommercegermanyawards.com/vote/134168

proof
![api eventjuicer com _ 502_ Bad gateway 2021-12-01 11-37-31](https://user-images.githubusercontent.com/75311923/144221596-ab2b66df-879e-404a-8da9-d96ee76446fd.png)

Severity/Priority
Critical

number of users already affected (reporting this issue) of total users
2 (chatlio)

team members who tested
MT, DK - now after the test whole team confirms that the voting is back online

**Comment by az** [comment]
server overload ....noticed and resolved

**Comment by az** [comment]
cause: faulty data update function - temporary solution - b25e2ffaf6b7fec30dd3d4515504546d1bd7b93a
