### ISSUE TITLE
Add banner directing to EBE registration page

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#89]
This month we will definitely see a huge increase in traffic on the EGA website - we need to use it for EBE visitor (free) registration and direct people to https://ecommerceberlin.com/visit 
There are two ways how to handle that and I'm open to discussion.

1. Screenshot of the registration form from EBE website, directing to the registration page - looking like the link below:
https://share.getcloudapp.com/nOu5OQYj

2. Use the banners we have prepared for promo - 
formats 1:1 and 4:1 https://drive.google.com/file/d/1v85lw-QAx1OZID7u-6lX5vCrWpnd0BRc/view?usp=sharing
format 6:1 https://drive.google.com/file/d/19RM1A_yxKPKPUf7n2xRxpE5Z4zAMU5Im/view?usp=sharing

**Comment by az** [comment]
@jprzybylski4 the only not anti-UX way would be homepage (nobody cares :)  and "onVoted" behaviour... as you probably recall we had such a reg form on EBE website  ("onVoted"  - shown in a dialog after voting process)

**Comment by az** [comment]
can you provide valid UTMs for better monitoring of directed traffic?

**Comment by jprzybylski4** [comment]
https://ecommerceberlin.com/visit?utm_source=EGAwards&utm_medium=banner_profile&utm_campaign=ega_banner_voting
It would be great if we could track from which exact profile the traffic came - is that possible?

**Comment by az** [comment]
@jprzybylski4 possible but structure via utm_term or utm_content cc @marek-berlin ?

**Comment by az** [comment]
@jprzybylski4 have you checked provided banners before posting them? 200mb of downloading to see banners with "VISIT OUR STAND?"

**Comment by az** [comment]
in the future please provide SEPARATE gfx in contemporary format like PDF/SVG. thx
