### ISSUE TITLE
Export the online voters list 

### ISSUE THREAD

**Issue by jprzybylski4** [ecommerceberlin/ecommercegermanyawards.com#99]
Please export the online voters list from EGA and CFP last editions. 
@mark will need for the event promo.

**Comment by az** [comment]
resolved via slack
![Slack | ecommerceberlin_it | fp20 | 51 new items 2022-02-23 10-42-50](https://user-images.githubusercontent.com/2198/155294485-3aca2923-f5e5-441e-a0ec-d414dbc36a27.jpg)
